package dev.tauri.jsg.core.common.registry.tag;

import dev.tauri.jsg.core.JSGCore;
import dev.tauri.jsg.core.mapping.JSGMapping;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

public class CoreItemTags {
    public static final TagKey<Item> CRYSTAL_FERTILIZERS = tag("crystal_fertilizers");
    public static final TagKey<Item> DUST_NAQUADAH_RAW = tag("dusts/naquadah");
    public static final TagKey<Item> DUST_NAQUADAH_ALLOY = tag("dusts/naquadah_alloy");
    public static final TagKey<Item> DUST_NAQUADAH_REFINED = tag("dusts/naquadah_refined");
    public static final TagKey<Item> DUST_TITANIUM = tag("dusts/titanium");
    public static final TagKey<Item> DUST_TRINIUM = tag("dusts/trinium");
    public static final TagKey<Item> DUSTS = tag("dusts");
    public static final TagKey<Item> GEAR_NAQUADAH = tag("gears/naquadah");
    public static final TagKey<Item> GEAR_NAQUADAH_ALLOY = tag("gears/naquadah_alloy");
    public static final TagKey<Item> GEAR_NAQUADAH_REFINED = tag("gears/naquadah_refined");
    public static final TagKey<Item> GEAR_TITANIUM = tag("gears/titanium");
    public static final TagKey<Item> GEAR_TRINIUM = tag("gears/trinium");
    public static final TagKey<Item> GEARS = tag("gears");
    public static final TagKey<Item> GEM_BLUE = tag("gems/blue");
    public static final TagKey<Item> GEM_BLUE_SMALL = tag("gems/blue_small");
    public static final TagKey<Item> GEM_ENDER = tag("gems/ender");
    public static final TagKey<Item> GEM_ENDER_SMALL = tag("gems/ender_small");
    public static final TagKey<Item> GEM_PEGASUS = tag("gems/pegasus");
    public static final TagKey<Item> GEM_PEGASUS_SMALL = tag("gems/pegasus_small");
    public static final TagKey<Item> GEM_RED = tag("gems/red");
    public static final TagKey<Item> GEM_RED_SMALL = tag("gems/red_small");
    public static final TagKey<Item> GEM_WHITE = tag("gems/white");
    public static final TagKey<Item> GEM_WHITE_SMALL = tag("gems/white_small");
    public static final TagKey<Item> GEM_YELLOW = tag("gems/yellow");
    public static final TagKey<Item> GEM_YELLOW_SMALL = tag("gems/yellow_small");
    public static final TagKey<Item> GEMS = tag("gems");
    public static final TagKey<Item> INGOT_COPPER_EXPOSED = tag("ingots/copper_exposed");
    public static final TagKey<Item> INGOT_COPPER_WEATHERED = tag("ingots/copper_weathered");
    public static final TagKey<Item> INGOT_COPPER_OXIDIZED = tag("ingots/copper_oxidized");
    public static final TagKey<Item> INGOT_NAQUADAH = tag("ingots/naquadah");
    public static final TagKey<Item> INGOT_NAQUADAH_ALLOY = tag("ingots/naquadah_alloy");
    public static final TagKey<Item> INGOT_NAQUADAH_REFINED = tag("ingots/naquadah_refined");
    public static final TagKey<Item> INGOT_TITANIUM = tag("ingots/titanium");
    public static final TagKey<Item> INGOT_TRINIUM = tag("ingots/trinium");
    public static final TagKey<Item> INGOTS = tag("ingots");
    public static final TagKey<Item> NUGGET_NAQUADAH = tag("nuggets/naquadah");
    public static final TagKey<Item> NUGGET_NAQUADAH_ALLOY = tag("nuggets/naquadah_alloy");
    public static final TagKey<Item> NUGGET_NAQUADAH_REFINED = tag("nuggets/naquadah_refined");
    public static final TagKey<Item> NUGGET_TITANIUM = tag("nuggets/titanium");
    public static final TagKey<Item> NUGGET_TRINIUM = tag("nuggets/trinium");
    public static final TagKey<Item> NUGGETS = tag("nuggets");
    public static final TagKey<Item> ORE_NAQUADAH = tag("ores/naquadah");
    public static final TagKey<Item> ORE_TITANIUM = tag("ores/titanium");
    public static final TagKey<Item> ORE_TRINIUM = tag("ores/trinium");
    public static final TagKey<Item> ORES = tag("ores");
    public static final TagKey<Item> ORE_RATES_SINGULAR = tag("ore_rates/singular");
    public static final TagKey<Item> ORE_IN_GROUND_DEEPSLATE = tag("ores_in_ground/deepslate");
    public static final TagKey<Item> ORE_IN_GROUND_ENDSTONE = tag("ores_in_ground/endstone");
    public static final TagKey<Item> ORE_IN_GROUND_NETHERRACK = tag("ores_in_ground/netherrack");
    public static final TagKey<Item> ORE_IN_GROUND_SANDSTONE = tag("ores_in_ground/sandstone");
    public static final TagKey<Item> ORE_IN_GROUND_STONE = tag("ores_in_ground/stone");
    public static final TagKey<Item> PLATE_NAQUADAH = tag("plates/naquadah");
    public static final TagKey<Item> PLATE_NAQUADAH_ALLOY = tag("plates/naquadah_alloy");
    public static final TagKey<Item> PLATE_NAQUADAH_REFINED = tag("plates/naquadah_refined");
    public static final TagKey<Item> PLATE_TITANIUM = tag("plates/titanium");
    public static final TagKey<Item> PLATE_TRINIUM = tag("plates/trinium");
    public static final TagKey<Item> PLATES = tag("plates");
    public static final TagKey<Item> RAW_MATERIAL_NAQUADAH = tag("raw_materials/naquadah");
    public static final TagKey<Item> RAW_MATERIAL_TITANIUM = tag("raw_materials/titanium");
    public static final TagKey<Item> RAW_MATERIAL_TRINIUM = tag("raw_materials/trinium");
    public static final TagKey<Item> RAW_MATERIALS = tag("raw_materials");
    public static final TagKey<Item> STORAGE_BLOCK_CRYSTAL_BLUE = tag("storage_blocks/blue_crystal");
    public static final TagKey<Item> STORAGE_BLOCK_CRYSTAL_ENDER = tag("storage_blocks/ender_crystal");
    public static final TagKey<Item> STORAGE_BLOCK_CRYSTAL_PEGASUS = tag("storage_blocks/pegasus_crystal");
    public static final TagKey<Item> STORAGE_BLOCK_CRYSTAL_RED = tag("storage_blocks/red_crystal");
    public static final TagKey<Item> STORAGE_BLOCK_CRYSTAL_WHITE = tag("storage_blocks/white_crystal");
    public static final TagKey<Item> STORAGE_BLOCK_CRYSTAL_YELLOW = tag("storage_blocks/yellow_crystal");
    public static final TagKey<Item> CRYSTAL_BLOCKS = tag("crystal_blocks");
    public static final TagKey<Item> STORAGE_BLOCK_RAW_ORE_NAQUADAH = tag("storage_blocks/raw_naquadah");
    public static final TagKey<Item> STORAGE_BLOCK_RAW_ORE_TITANIUM = tag("storage_blocks/raw_titanium");
    public static final TagKey<Item> STORAGE_BLOCK_RAW_ORE_TRINIUM = tag("storage_blocks/raw_trinium");
    public static final TagKey<Item> STORAGE_BLOCK_NAQUADAH = tag("storage_blocks/naquadah");
    public static final TagKey<Item> STORAGE_BLOCK_NAQUADAH_ALLOY = tag("storage_blocks/naquadah_alloy");
    public static final TagKey<Item> STORAGE_BLOCK_NAQUADAH_REFINED = tag("storage_blocks/naquadah_refined");
    public static final TagKey<Item> STORAGE_BLOCK_TITANIUM = tag("storage_blocks/titanium");
    public static final TagKey<Item> STORAGE_BLOCK_TRINIUM = tag("storage_blocks/trinium");
    public static final TagKey<Item> STORAGE_BLOCKS = tag("storage_blocks");
    public static final TagKey<Item> TOOL_WRENCH = tag("tools/wrench");
    public static final TagKey<Item> FLUID_CAULDRON_HEATING = tag("fluid_cauldron_heating");

    private static TagKey<Item> tag(String name) {
        return ItemTags.create(JSGMapping.rl(JSGCore.MOD_ID, name));
    }
}
